/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppBatchesRouteImport } from './routes/app/batches'
import { Route as AppColdChainRouteImport } from './routes/app/cold-chain'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSalesRouteImport } from './routes/app/sales'
import { Route as AppSuppliersRouteImport } from './routes/app/suppliers'
import { Route as TraceCodeRouteImport } from './routes/trace.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesRoute = AppBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppRoute,
} as any)
const AppColdChainRoute = AppColdChainRouteImport.update({
  id: '/cold-chain',
  path: '/cold-chain',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const TraceCodeRoute = TraceCodeRouteImport.update({
  id: '/trace/$code',
  path: '/trace/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/enter': typeof EnterRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/batches': typeof AppBatchesRoute
  '/app/cold-chain': typeof AppColdChainRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/trace/$code': typeof TraceCodeRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enter': typeof EnterRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/batches': typeof AppBatchesRoute
  '/app/cold-chain': typeof AppColdChainRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/trace/$code': typeof TraceCodeRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/enter': typeof EnterRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/batches': typeof AppBatchesRoute
  '/app/cold-chain': typeof AppColdChainRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/trace/$code': typeof TraceCodeRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/enter'
    | '/app/alerts'
    | '/app/batches'
    | '/app/cold-chain'
    | '/app/customers'
    | '/app/inventory'
    | '/app/payments'
    | '/app/reports'
    | '/app/sales'
    | '/app/suppliers'
    | '/trace/$code'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enter'
    | '/app/alerts'
    | '/app/batches'
    | '/app/cold-chain'
    | '/app/customers'
    | '/app/inventory'
    | '/app/payments'
    | '/app/reports'
    | '/app/sales'
    | '/app/suppliers'
    | '/trace/$code'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/enter'
    | '/app/alerts'
    | '/app/batches'
    | '/app/cold-chain'
    | '/app/customers'
    | '/app/inventory'
    | '/app/payments'
    | '/app/reports'
    | '/app/sales'
    | '/app/suppliers'
    | '/trace/$code'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EnterRoute: typeof EnterRoute
  TraceCodeRoute: typeof TraceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches': {
      id: '/app/batches'
      path: '/batches'
      fullPath: '/app/batches'
      preLoaderRoute: typeof AppBatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cold-chain': {
      id: '/app/cold-chain'
      path: '/cold-chain'
      fullPath: '/app/cold-chain'
      preLoaderRoute: typeof AppColdChainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/trace/$code': {
      id: '/trace/$code'
      path: '/trace/$code'
      fullPath: '/trace/$code'
      preLoaderRoute: typeof TraceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBatchesRoute: typeof AppBatchesRoute
  AppColdChainRoute: typeof AppColdChainRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBatchesRoute: AppBatchesRoute,
  AppColdChainRoute: AppColdChainRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EnterRoute: EnterRoute,
  TraceCodeRoute: TraceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
